# Tensor 생성

##  원하는 형태(shape) 텐서 생성
- **torch.tensor(자료구조)**
## 특정 타입의 Tensor 생성
- **torch.FloatTensor(자료구조)**
    - float 타입 텐서 생성
- **torch.longTensor(자료구조)** 
    - int 타입 텐서생성
    
## tensor 상태 조회
- **tensor.shape, tensor.size()**: tensor의 shape조회
- **tensor.dtype, tensor.type()**: tensor 원소들의 데이터타입 조회
- **tensor.ndim, tensor.dim()**  : tensor 차원
- **tensor.numel()**: 전체 원소 개수


In [1]:
import torch

In [2]:
print('hi')

hi


In [3]:
a = torch.tensor([[1,2],[3,4]], dtype=torch.float32)
print("shape:", a.shape, a.size())
print("축별 크기:", a.shape[0], a.size(0))
print("type:", a.type(), a.dtype)
print('차원크기:', a.dim(), a.ndim)
print('원소개수:', a.numel())

shape: torch.Size([2, 2]) torch.Size([2, 2])
축별 크기: 2 2
type: torch.FloatTensor torch.float32
차원크기: 2 2
원소개수: 4


In [7]:
torch.tensor(range(10))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
a2 = torch.tensor(range(10), dtype=torch.float64)
print('type:', a2.type(), a2.dtype)

type: torch.DoubleTensor torch.float64


In [8]:
#Float/Long(실수, 정수) type Tensor
b = torch.FloatTensor([1,3,7])  #float32
print(b.dtype)
c = torch.LongTensor([10,20,30]) # int64
print(c.dtype)

torch.float32
torch.int64


## 특정 값으로 구성된 Tensor 생성
- **torch.zeros(), zeros_like()**: 0으로 구성된 tensor 생성
- **torch.ones(), ones_like()**: 1로 구성된 tensor생성
- **torch.full(), full_like**: 지정한 값으로 구성된 tensor생성
    

In [9]:
torch.zeros(3,2,3)
# torch.ones(2,3)
# torch.full((3,2), fill_value=100)


tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [10]:
a = torch.tensor([[1, 2],[3,4]])
print(a.shape)
b = torch.zeros_like(a)
# b = torch.ones_like(a)
# b = torch.full_like(a, 20)
b.shape

torch.Size([2, 2])


torch.Size([2, 2])

## 동일한 간격으로 떨어진 값들로 구성된 배열생성
- **torch.linspace()**
- **torch.arange()**

In [67]:
# torch.arange(10)
# torch.arange(0, 1, 0.1)
torch.arange(10, 1, -1)

tensor([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [12]:
torch.linspace(0, 10, 5)
# torch.linspace(0, 1, 11)


tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

## 빈 tensor 생성
- **torch.empty()**

In [13]:
torch.empty((3,2))

tensor([[1.9215e-34, 0.0000e+00],
        [1.9211e-34, 0.0000e+00],
        [0.0000e+00, 0.0000e+00]])

## 난수를 이용한 생성

- **torch.rand()**: 0 ~ 1사이 실수로 구성된 배열을 생성. 각 값은 균등분포를 따른다.
- **torch.randn()**: 표준정규분포(평균:0, 표준편차:1)를 따르는 실수로 구성된 배열 생성
- **torch.randint()**: 지정한 범위의 정수로 구성된 배열 생성
- **torch.randperm(n)**: 0 ~ n 사이의 정수를 섞은 값을 원소로 가지는 배열 생성

In [71]:
torch.manual_seed(1004)  # seed 설정
torch.rand(100)                 # 0~1 사이의 균일분포, (행, 열)
torch.randn(4,4)                # (행, 열)
# torch.randint(1, 10, (3,3))   # 1~10 사이의 균일분포 정수, (행, 열)
# torch.randperm(5)             # 0~4 까지의 랜덤한 순열

tensor([[-0.6345, -0.1462, -0.1406, -0.2666],
        [-0.8307,  0.1198, -2.1087, -0.7709],
        [ 0.0675, -0.0102,  0.3949,  1.8961],
        [-0.2829,  1.0345,  0.0224, -0.5187]])

## tensor를 상수로 변환
- tensor.item()
    - 상수 tensor를 python 상수로 변환

In [15]:
a = torch.tensor(10)
print(a)
print(a.item())

tensor(10)
10


In [16]:
b = torch.tensor([20])
print(b)
print(b.item()) #원소가 하나인 배열 변환 가능

tensor([20])
20


In [17]:
c = torch.tensor([1, 10, 100])
print(c)
# print(c.item()) #원소가 여러개일 경우 Exception발생

tensor([  1,  10, 100])


In [18]:
d = torch.tensor([10], device='cuda')
print(d)
print(d.item())

tensor([10], device='cuda:0')
10


In [ ]:
# 텐서 ram -> vram
a = torch.tensor([1,2,3])
a.to('cuda')
# a.to('cuda:0')
# 텐서 vram -> ram
a.cpu()
# a.to('cpu')

## ndarray 호환

- ndarray를 tensor로 생성
    - **torch.tensor(ndarray)**
    - **torch.from_numpy(ndarray)**
- tensor를 ndarray로 변환
    - **ndarray.numpy()**
    - tensor가 gpu에 있을 경우 cpu로 옮긴 뒤 변환해야 한다.

In [4]:
import numpy as np
import torch

In [20]:
# ndarray -> tensor
arr = np.arange(1,10)

torch.tensor(arr)
torch.from_numpy(arr)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# tensor -> ndarray
t = torch.randn(3,3)
print(t)
t.numpy()

tensor([[ 0.0444,  0.5274,  0.0708],
        [-1.1345, -0.7744, -1.5946],
        [-2.0639,  0.9306,  1.0121]])


array([[ 0.04439625,  0.5274427 ,  0.07080834],
       [-1.1344635 , -0.7743912 , -1.5945598 ],
       [-2.0638611 ,  0.930639  ,  1.0120598 ]], dtype=float32)

In [8]:
t2 = torch.randn(2,2, device="cuda")
t2

tensor([[ 0.4723, -0.1650],
        [-0.1920,  1.0036]], device='cuda:0')

In [9]:
t2.numpy() 
# t2.to("cpu").numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [10]:
t2.cpu().numpy()

array([[ 0.47229606, -0.1650249 ],
       [-0.1919779 ,  1.0035707 ]], dtype=float32)

In [11]:
t2.to("cpu").numpy()

array([[ 0.47229606, -0.1650249 ],
       [-0.1919779 ,  1.0035707 ]], dtype=float32)

## Tensor gpu/cpu 메모리로 옮기기

- pytorch는 데이터셋인 tensor를 cpu메모리와 gpu 메모리로 옮길 수 있다.
    - 데이터에 대한 연산처리를 어디서 하느냐에 따라 메모리를 선택한다.
    - 장치는 문자열로 설정한다.
        - CPU 사용: "cpu"
        - nvida GPU: "cuda"
        - Apple m1: "mps"
            - pytorch 1.12 부터 지원
- 옮기기
    - tensor 생성시 `device` 파라미터를 이용해 설정
    - `tensor.to(device)`를 이용해 설정
- 현재 실행환경에서 어떤 장비를 사용할 수 있는지 확인
    - nvidia gpu 사용가능확인
        - `torch.cuda.is_available()` - nvida gpu 사용가능 여부
        - `torch.backends.mps.is_available()` - M1 사용가능 여부

In [13]:
!nvidia-smi

Thu Jun  1 05:30:06 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   54C    P0    29W /  70W |    121MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [20]:
# cuda 환경 확인 -> rocm도 cuda호환됨.
torch.cuda.is_available()

True

In [21]:
# apple m1 환경 확인
torch.backends.mps.is_available()

False

In [12]:
device = 'cuda' if torch.cuda.is_available() else 'mps' if torch.backends.mps.is_available() else 'cpu'
device

'cuda'

In [18]:
t = torch.tensor([1, 2, 3], dtype=torch.float32, device=device)
t.device

device(type='cuda', index=0)

In [17]:
t2 = t.to("cpu")
t2.device

device(type='cpu')

In [19]:
t2.numpy()

array([1., 2., 3.], dtype=float32)

# 원소 조회및 변경 - indexing/slicing

- 대부분 Numpy 와 동일
    - slicing에서 step을 음수로 지정할 수 없다.


In [29]:
t = torch.randint(-10, 10, (100, ))
t

tensor([ -4,   4,  -9,   9,  -4,  -9,  -3,  -3,   4,  -9,  -2,  -9,   1,   2,
          6,  -9,   5,  -9,   1,  -4,  -9,   1,   5,  -1,  -8,  -2,  -5,  -6,
          3,  -3,   4, -10,   0,  -2,  -4,   0,  -8,   4,  -6,   9,  -8,  -2,
          8,   9,  -7,   0,  -2,   6,  -3,   6,   5, -10,   7,  -6,   3,   7,
          6,   7,   2,   1,  -2,   0,   6,   9,  -9,   0,  -8,  -6,  -8,  -2,
          6,  -2,  -4,   4,  -4,   5,   4, -10,  -9,  -4,   0,  -3,   5,   2,
         -2,  -1,   2,   5,  -5, -10,  -2,  -5,   5,   1, -10,   1,  -8,   1,
         -7,   2])

In [30]:
t[0], t[[1, 5, -1]]

(tensor(-4), tensor([ 4, -9,  2]))

In [31]:
t[:5]
t[10:15]
t[90:]
t[3:30:3]
# t[10:1:-2]  #에러
t[1:10:2].flip(dims=(0,))#reverse

tensor([-9, -3, -9,  9,  4])

In [32]:
# boolean index
t[t > 0]

tensor([4, 9, 4, 1, 2, 6, 5, 1, 1, 5, 3, 4, 4, 9, 8, 9, 6, 6, 5, 7, 3, 7, 6, 7,
        2, 1, 6, 9, 6, 4, 5, 4, 5, 2, 2, 5, 5, 1, 1, 1, 2])

In [33]:
# 변경
t[0] = 100
t

tensor([100,   4,  -9,   9,  -4,  -9,  -3,  -3,   4,  -9,  -2,  -9,   1,   2,
          6,  -9,   5,  -9,   1,  -4,  -9,   1,   5,  -1,  -8,  -2,  -5,  -6,
          3,  -3,   4, -10,   0,  -2,  -4,   0,  -8,   4,  -6,   9,  -8,  -2,
          8,   9,  -7,   0,  -2,   6,  -3,   6,   5, -10,   7,  -6,   3,   7,
          6,   7,   2,   1,  -2,   0,   6,   9,  -9,   0,  -8,  -6,  -8,  -2,
          6,  -2,  -4,   4,  -4,   5,   4, -10,  -9,  -4,   0,  -3,   5,   2,
         -2,  -1,   2,   5,  -5, -10,  -2,  -5,   5,   1, -10,   1,  -8,   1,
         -7,   2])

In [34]:
t = torch.arange(1, 10).reshape(3,3)
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [35]:
t[[1,0], [2,2]]  #(1,2), (0,2)

tensor([6, 3])

# Reshape

## shape 변경
- reshape() / view() 이용
    - 변환 후 값을 변경하면 원본 배열의 값도 같이 바뀐다.
 > tensor.clone(): tensor를 복제한다.

In [36]:
a=torch.rand(12)
a2 = a.reshape(3,4)
a3 = a.reshape((3,2,2))
a4 = a.reshape((3,2,-1))  #한개 axis는 -1로 설정가능
print(a.shape, a2.size(), a3.shape, a4.shape)
               

torch.Size([12]) torch.Size([3, 4]) torch.Size([3, 2, 2]) torch.Size([3, 2, 2])


In [37]:
a5 = a.view(3,4)
a6 = a.view((3,2,2))
a7 = a.view((3,2,-1))  #한개 axis는 -1로 설정가능
print(a.shape, a5.size(), a6.shape, a7.shape)

torch.Size([12]) torch.Size([3, 4]) torch.Size([3, 2, 2]) torch.Size([3, 2, 2])


In [38]:
a

tensor([0.5081, 0.7115, 0.1617, 0.7022, 0.1623, 0.5625, 0.9652, 0.3692, 0.9346,
        0.9708, 0.7656, 0.9052])

In [39]:
a5[0, 0] = 12.1
a2[0, 1] = 15.1

print(a)

tensor([12.1000, 15.1000,  0.1617,  0.7022,  0.1623,  0.5625,  0.9652,  0.3692,
         0.9346,  0.9708,  0.7656,  0.9052])


In [40]:
# tensor복사: clone() 메소드
r = a.clone().reshape(3,4)
r[0,0] = 100.1
print(a)

tensor([12.1000, 15.1000,  0.1617,  0.7022,  0.1623,  0.5625,  0.9652,  0.3692,
         0.9346,  0.9708,  0.7656,  0.9052])


## dummy 축 늘리기

- None을 이용
- unsqueeze()

In [41]:
import torch
a = torch.tensor([[10,20],[10,20]])
print(a.shape)

# a1, a2 = a[None, :], torch.unsqueeze(a, dim=0)
# print(a1.shape, a2.shape)

# a3, a4 = a[:, :, None], torch.unsqueeze(a, dim=-1)  #None 사용시 모든 축에 :를 붙인다.
# print(a3.shape, a4.shape)

# a5, a6 = a3[:,None,:,:], torch.unsqueeze(a3, dim=1)
# print(a5.shape, a6.shape)

torch.Size([2, 2])


## dummy 축 제거
- `squeeze()` 이용

In [42]:
t = torch.rand(3, 1, 3, 1)
print(t.shape)

# r1 = t.squeeze()  #모두 제거
# print(r1.shape)

# r2 = t.squeeze(dim=1) # 특정 axis 제거
# print(r2.shape)

# r3 = t.squeeze(dim=[1,3]) # 여러 axis의 dummy 축 제거
# print(r3.shape)

torch.Size([3, 1, 3, 1])


## tensor 합치기
torch.cat([tensorA, tensorB, ...], dim=0)

In [43]:
a = torch.arange(10).reshape(2,5)
b = torch.arange(10,20).reshape(2,5)
c = torch.arange(20,30).reshape(2,5)
d = torch.arange(10,19).reshape(3,3)
print(a)
print(b)
print(c)
print(d)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
tensor([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]])
tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])


In [44]:
torch.cat([a, b], dim=0) # dim 대신 axis사용가능

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [45]:
torch.cat([a, b, c], dim=0)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]])

In [46]:
torch.cat([a, b], axis=1) # dim 대신 axis사용가능

tensor([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
        [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [47]:
torch.cat([a, b, c], axis=1)

tensor([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24],
        [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19, 25, 26, 27, 28, 29]])

In [48]:
torch.cat([a, b], axis=-1)

tensor([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
        [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [49]:
# torch.cat([a, d])  #Error

## 축변경
- tensor.transpose(axis1, axis2) 
    - tensor의 두 축의 자리를 변경한다. 
- tensor.permute(axis1, axis2, axis3, ..)
    - tensor의 두개 이상의 축의 자리를 변경한다.

In [50]:
X = torch.arange(24).reshape(2, 3, 4)
print(X.shape)

# y = X.transpose(1, 2)
# print(y.shape)

# z = X.permute(2, 0, 1)
# print(z.shape)

torch.Size([2, 3, 4])


# tensor 연산 및 주요 함수

## element-wise 연산
- tensor와 상수 연산시, tensor와 tensor간 연산시 원소별로 처리한다.
- 행렬곱 연산을 제외하고 tensor간 연산시 피연산지 tensor간에 shape이 같아야 한다.
    - shape이 다를 경우 조건이 맞으면 broadcasting을 한 뒤에 연산한다. (size가 다른 축의 경우 한개의 피연산자 size가 1일 경우 복사하여 shape을 맞춘다.)
    

In [51]:
import torch

a = torch.arange(10).reshape(2,5)
b = torch.arange(10,20).reshape(2,5)
c = torch.arange(50, 55)

print(a)
print(b)
print(c)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
tensor([50, 51, 52, 53, 54])


In [52]:
print(a + 100)
# print(a - 100)
# print(a < 5)

tensor([[100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109]])


In [53]:
print(a + b)
# print(a == b)

tensor([[10, 12, 14, 16, 18],
        [20, 22, 24, 26, 28]])


In [54]:
# broadcasting
print(a + c)

tensor([[50, 52, 54, 56, 58],
        [55, 57, 59, 61, 63]])


## 주요 연산자

In [55]:
x=torch.arange(-4, 5).reshape(3,3)
y = x + torch.randn((3,3))
print(x)
print(torch.abs(x))
# print(torch.sqrt(torch.abs(x)))
# print(torch.exp(x))  # torch.e**x
# print(torch.log(torch.abs(x)))
# print(torch.log(torch.exp(torch.tensor(1)))) # torch.log() 밑이 e인 로그계산
# print(torch.log10(torch.tensor(10)))         # torch.log10() 밑이 10인 로그계산
# print(torch.log2(torch.tensor(2)))           # torch.log2() 밑이 2인 로그계산
# print("=====================")
# print(y)
# print(torch.round(y)) # 반올림
# print(torch.round(y, decimals=2)) # 소수점 둘째자리까지
# print(torch.floor(y)) # 내림
# print(torch.ceil(y)) # 올림

tensor([[-4, -3, -2],
        [-1,  0,  1],
        [ 2,  3,  4]])
tensor([[4, 3, 2],
        [1, 0, 1],
        [2, 3, 4]])


## torch.nan, torch.inf
- nan: Not a Number, 주로 결측치를 표현한다.
- inf: infinit 무한. 
    - torch.inf: 양의 무한
    - -torch.inf: 음의 무한
- torch.isnan(tensor)
    - 원소별 결측치 확인
- torch.isinf(tensor)    
    - 원소별 inf 확인

In [56]:
print(torch.inf > 10, torch.inf < 10)
print(-torch.inf < 10, -torch.inf > 10)

True False
True False


In [57]:
print(torch.log(torch.tensor(-1))) # nan 
# print(torch.isnan(torch.tensor([1,2,torch.nan,3,4])))  # nan 여부 확인
# print(torch.isinf(torch.tensor([1,2,3,4,torch.inf])))  # inf 여부 확인

tensor(nan)


## 기술통계함수

In [58]:
X=torch.randn(3,4)
print(X)

tensor([[ 0.9997, -0.5608,  0.4931, -2.3516],
        [-0.4303, -0.6405, -0.7833, -0.4779],
        [ 2.0895, -1.4722, -0.5257,  0.0826]])


In [59]:
print(torch.sum(X))
# print(torch.sum(X, dim=1))
# print(torch.sum(X, dim=1,keepdims=True))

# print(torch.mean(X))
# print(torch.mean(X, dim=1))
# print(torch.mean(X, dim=1,keepdims=True))

# print(torch.std(X)) # standard deviation 표준 편차
# print(torch.var(X)) # variance
# print(torch.var(X, dim=0))

# print(X.sum(dim=1, keepdims=True))
# print(X.mean(dim=1, keepdims=True))
# print(X.std())

tensor(-3.5774)


In [60]:
# print(torch.max(X))
# print(torch.max(X, dim=0))  # return_types.max 타입객체로 반환. max값과 max값의 index를 묶어서 반환
# print(torch.max(X, dim=1))
# print(torch.max(X, dim=1).values, torch.max(X, dim=1).indices, sep=" || ")
# print(torch.max(X, dim=0, keepdims=True))  #keepdims=True : 차원(rank)를 유지
# # print(torch.max(X, dim=1, keepdims=True))

# print(torch.min(X))
# print(torch.min(X, dim=0))
# print(torch.min(X, dim=1))

# print(torch.argmax(X))
# print(torch.argmax(X, dim=0)) # 각 열에서 가장 큰 애가 존재하는 인덱스
# print(torch.argmax(X, dim=1)) # 각 행에서 가장 큰 애가 존재하는 인덱스

## 선형회귀

### 행렬곱
- `@` 연산자 또는 `torch.matmul(tensor1, tensor2)` 함수 이용

In [61]:
import torch

In [62]:
x = torch.FloatTensor([[1, 2],
                       [3, 4],
                       [5, 6]
                      ])

y = torch.FloatTensor([[1, 2],
                       [1, 2],
                      ])
x.size(), y.shape

(torch.Size([3, 2]), torch.Size([2, 2]))

In [63]:
z1 = x @ y
z2 = torch.matmul(x, y)
print(z1.shape, z2.shape)
print(z1)
print(z2)

torch.Size([3, 2]) torch.Size([3, 2])
tensor([[ 3.,  6.],
        [ 7., 14.],
        [11., 22.]])
tensor([[ 3.,  6.],
        [ 7., 14.],
        [11., 22.]])


In [64]:
# Batch 행렬곱(Batch matrix muliplication)
# x, y가 가지는 3개의 2차원 배열 간에 행렬곱을 처리한다.
x = torch.FloatTensor(3,4,2)
y = torch.FloatTensor(3,2,5)
z = torch.bmm(x, y)
z.shape

torch.Size([3, 4, 5])

# autograd(자동미분)
- 자동 미분을 이용해 gradient를 계산하는 pytorch system.
- 딥러닝 모델에서 weight와 bias tensor들은 backpropagation(역전파)를 이용해 gradient를 구해서 loss가 줄어드는 방향으로 update를 하게된다.
- pytorch는 이런 미분 수행을 자동으로 처리해 준다.
    - gradient(기울기)를 구한다는 것은 미분을 한다는 것을 말한다.
- tensor가 미분 가능하려면 `requires_grad=True` 로 설정되 있어야 한다. (default: False)
    

In [ ]:
x = torch.tensor([1.], requires_grad=True)
# x = torch.tensor([1.])
# x.requires_grad = True
print(x)
print(x.requires_grad)

In [ ]:
y = x ** 2
print(y)
# 계산 결과를 담은 tensor인 y는 계산 결과와 grad_fn에 어떤 계산을 했는지 정보를 담고 있다. (PowBackward0)
# 이는 y 계산에 사용된 x가 requires_grad=True이기 때문이다.

In [ ]:
# 미분 - tensor.backward() 호출
y.backward()   # dy/dx  gradient 계산 후 결과를 x의 grad attribute에 저장한다.

In [ ]:
x.grad
# 도함수: y` = 2x 이고 x가 1이었으므로 grad는 2

In [ ]:
# requires_grad가 True로 설정되 있느 않은 경우
# x = torch.tensor([1.])
# y = x ** 2
# y.backward()

In [ ]:
x = torch.tensor([1.], requires_grad=True)
y = x ** 2   # 미분: 2x
z = y * 10   # 미분: 10  ===> 2x * 10

z.backward()
print(x.grad)

In [ ]:
## 편미분
x=torch.tensor([1.],requires_grad=True)
y=torch.tensor([1.],requires_grad=True)
z= 2*x**2 + y**2
print(z)
z.backward() 
print(x.grad)  #dz/dx
print(y.grad)  #dz/dy

In [ ]:
x=torch.tensor([1., 2., 3.] ,requires_grad=True)
y=torch.sum(x**2) # [x1**2 + x2**2 + x3**2]  
y.backward() #[dy/dx1, dy/dx2, dy/dx3] = [2x1, 2x2, 2x3]

print(y)
print(x.grad) # 스칼라를 벡터로 미분

## torch.no_grad() 
- no_grad() 구문에서 연산을 할 겨우 requires_grad=True로 설정되었다 하더라도 gradient를 update하지 않는다.
- 딥러닝 모델 학습이 끝나고 평가할 때는 gradient를 계산할 필요가 없기 때문에 no_grad 구문을 사용한다.


In [ ]:
x = torch.tensor(1.0, requires_grad = True)
print(x.requires_grad)


print(x.requires_grad)
y = x**2
print(y.requires_grad)  # 연산이 결과 requires_grad도 True -> 그래야 미분이 가능하므로.

print(x.requires_grad)
y.backward()
print(x.grad)


In [ ]:
x = torch.tensor(1.0, requires_grad = True)
print(x.requires_grad)

with torch.no_grad():
    print(x.requires_grad)
    y = x**2
    print(y.requires_grad)# 연산이 적용될 때 requires_grad가 False가 된다.
print(x.requires_grad)
# y.backward()


## gradient 값 초기화

In [ ]:
x = torch.tensor(1., requires_grad=True)
y = x**2
y.backward()
print("x의 gradient값:", x.grad )

In [ ]:
x

In [ ]:
z = x **2
z.backward()
print("x의 gradient값:", x.grad )


In [ ]:
x = torch.tensor(1., requires_grad=True)
y = x**2
y.backward()
x.grad

In [ ]:
# gradient초기화
x.grad = torch.tensor(0.)   
z = x**2
z.backward()
x.grad